apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{ .Values.ingressHost }}
      http:
        paths:
          - path: /api(/|$)(.*)
            backend:
              serviceName: {{ .Values.name }}
              servicePort: {{ .Values.port }}